#!/bin/sh

# this script installs the Generator Connector mechanism
# which connects the generator digital input to the generator manual control

guiFile="/opt/victronenergy/gui/qml/OverviewGenerator.qml"
generatorFile="/opt/victronenergy/dbus-generator-starter/startstop.py"

packageLogFile="/var/log/dbus-generator-starter/current"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    # display innitial message
    echo
    echo "The Generator Connector mechanism connects the generator digital input"
    echo "to the generator control manual start"
    echo "When the digial input changes to the running state,"
    echo "Venus Manual Start is changed to true if there are no automatic run conditions"
    echo "When the digital input changes to the not running,"
    echo "Venus Manual Start is changed to false"
    
    standardActionPrompt
fi

#### installing
if [ $scriptAction == 'INSTALL' ] ; then
    actionText="Activating GeneratorConnector"

    updateActiveFile "$guiFile"
    updateActiveFile "$generatorFile"
    logMessage "++ setup: Installed GeneratorConnector"
fi

# uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    restoreActiveFile "$guiFile"
    restoreActiveFile "$generatorFile"
    logMessage "++ setup: Uninstalled GeneratorConnector"
fi

if $filesUpdated ; then
    logMessage "restarting dbus_generator"
    svc -t /service/dbus-generator-starter
    restartGui=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript
